In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding 

2024-03-15 20:04:15.645786: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [6]:
vocab_size = 30
encoded_review = [one_hot(d, vocab_size) for d in reviews]
encoded_review

[[6, 19],
 [10, 20],
 [14, 4],
 [13, 4, 13],
 [26, 22, 21],
 [8, 19],
 [10, 22, 4],
 [27, 28],
 [27, 2],
 [27, 18]]

# Some sentences are three words and some are two words, we need to pad it

In [8]:
max_length = 3
padded_reviews = pad_sequences(encoded_review, maxlen=max_length, padding='post') # padd the reviews towards end
padded_reviews

array([[ 6, 19,  0],
       [10, 20,  0],
       [14,  4,  0],
       [13,  4, 13],
       [26, 22, 21],
       [ 8, 19,  0],
       [10, 22,  4],
       [27, 28,  0],
       [27,  2,  0],
       [27, 18,  0]], dtype=int32)

## Enbed vector size and create the model

In [13]:
embedded_vector_size = 4 

model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length, name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))


In [14]:
X = padded_reviews
y = sentiment

In [17]:
model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_1 (Flatten)         (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133 (532.00 Byte)
Trainable params: 133 (532.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.fit(X,y, epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 509ms/step - loss: 0.6993 - accuracy: 0.3000
Epoch 2/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6979 - accuracy: 0.3000
Epoch 3/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6965 - accuracy: 0.3000
Epoch 4/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6951 - accuracy: 0.4000
Epoch 5/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6937 - accuracy: 0.4000
Epoch 6/50
1/1 [==============================] - 0s 6ms/step - loss: 0.6923 - accuracy: 0.4000
Epoch 7/50
1/1 [==============================] - 0s 6ms/step - loss: 0.6910 - accuracy: 0.4000
Epoch 8/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6896 - accuracy: 0.4000
Epoch 9/50
1/1 [==============================] - 0s 6ms/step - loss: 0.6882 - accuracy: 0.3000
Epoch 10/50
1/1 [==============================] - 0s 6ms/step - loss: 0.6868 - accuracy: 0.4000
Epoch 11/50
1/1 [====================

In [21]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [22]:
weights[6] # nice 

array([-0.05610292, -0.01572768,  0.02806821, -0.05954644], dtype=float32)

In [23]:
weights[19] #  food

array([ 0.01087952,  0.01683817,  0.01058768, -0.05015176], dtype=float32)

In [ ]:
# amazing